### PR TITLE
Added fixed window length support

### PR DESCRIPTION
**Pull request by himanshu219**

### CODE REVIEW

**Review by JKashyap96 — APPROVED** [review]
LGTM

**Comment by icco** [comment]
@JKashyap96 could we merge this?

**Comment by himanshu219** [comment]
@icco  actually we fixed this for one customer and we were waiting for customer's response but the customer didn't responded back. Internally we do not have that much data in our dev atlas environment so we wanted to run it with some customer. Will you be able to try out this fix I'll be happy to share the new version whl package or you can directly copy paste api.py in your lambda or site packages (onprem) environment.

**Comment by icco** [comment]
@himanshu219 we run this job in a docker container that installs the pypi package via pip. Happy to test it though. I'm nat@laurel.ai if you wanna reach out and we can try testing.

**Pull request merged**
